trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '/API/Client/Service/*'
      - '../../../../Common/Services/*'
      - '../../../../Common/Database/*'
      - '../../../../Integrations/GoogleMapsClient/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/API/Client/Service/Function'
  packageName: 'ClientService'

steps:
  - template: ../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml